### ISSUE TITLE
fusion-icon crashes when XDG_CURRENT_DESKTOP is not set

### ISSUE THREAD

**Issue by dkoukola** [raveit65/fusion-icon#1]
Traceback (most recent call last):
  File "./fusion-icon", line 57, in <module>
    from FusionIcon.interface import choose_interface
  File "/tmp/fusion-icon/FusionIcon/interface.py", line 22, in <module>
    from util import env
  File "/tmp/fusion-icon/FusionIcon/util.py", line 25, in <module>
    from environment import env
  File "/tmp/fusion-icon/FusionIcon/environment.py", line 141, in <module>
    env = Environment()
  File "/tmp/fusion-icon/FusionIcon/environment.py", line 51, in __init__
    elif os.getenv('XDG_CURRENT_DESKTOP').endswith('GNOME') or os.getenv('GNOME_DESKTOP_SESSION_ID') is not None:
AttributeError: 'NoneType' object has no attribute 'endswith'

**Comment by soreau** [comment]
It probably should check if XDG_CURRENT_DESKTOP is not None first
